#!/usr/bin/env python3
"""Agent Actions — generate notes, flashcards, study guides, and quizzes."""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

DATA_DIR = Path.home() / ".floating-ai-tutor"
NOTES_DIR = DATA_DIR / "notes"
FLASHCARDS_DIR = DATA_DIR / "flashcards"
GUIDES_DIR = DATA_DIR / "study_guides"
QUIZZES_DIR = DATA_DIR / "quizzes"


def _ensure_dirs():
    for d in [NOTES_DIR, FLASHCARDS_DIR, GUIDES_DIR, QUIZZES_DIR]:
        d.mkdir(parents=True, exist_ok=True)


def generate_study_notes(topic: str, content: str = "") -> str:
    """Generate structured study notes from captured content."""
    _ensure_dirs()
    filename = f"{topic.replace(' ', '_').lower()}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    path = NOTES_DIR / filename

    notes = f"""# Study Notes: {topic.title()}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Key Concepts

{content[:500] if content else 'Capture screen content to generate detailed notes.'}

## Summary

- Main topic: {topic}
- Review these notes regularly
- Use flashcards for memorization

---
Generated by Floating AI Tutor
"""
    path.write_text(notes, encoding="utf-8")
    return str(path)


def generate_flashcards(topic: str, items: list[dict] | None = None) -> str:
    """Generate flashcards for a topic."""
    _ensure_dirs()
    filename = f"{topic.replace(' ', '_').lower()}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    path = FLASHCARDS_DIR / filename

    if not items:
        items = [
            {"front": f"What is {topic}?", "back": f"A fundamental concept in {topic} that forms the basis for understanding."},
            {"front": f"Key principle of {topic}", "back": "Understanding the core principles enables practical application."},
            {"front": f"Common use case for {topic}", "back": "Applied in real-world scenarios to solve specific problems."},
        ]

    deck = {
        "topic": topic,
        "created_at": datetime.now().isoformat(),
        "cards": items,
    }
    path.write_text(json.dumps(deck, indent=2, ensure_ascii=False), encoding="utf-8")
    return str(path)


def generate_study_guide(topic: str, content: str = "") -> str:
    """Generate a comprehensive study guide."""
    _ensure_dirs()
    filename = f"{topic.replace(' ', '_').lower()}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    path = GUIDES_DIR / filename

    guide = f"""# Study Guide: {topic.title()}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Learning Objectives
- Understand the fundamentals of {topic}
- Apply {topic} concepts in practical scenarios
- Master advanced techniques in {topic}

## Core Content
{content[:800] if content else 'Capture screen content to generate a detailed study guide.'}

## Practice Exercises
1. Explain {topic} in your own words
2. Find a real-world example of {topic}
3. Apply {topic} to solve a problem

## Review Checklist
- [ ] Core concepts understood
- [ ] Practice exercises completed
- [ ] Flashcards reviewed
- [ ] Quiz attempted

---
Generated by Floating AI Tutor
"""
    path.write_text(guide, encoding="utf-8")
    return str(path)


def generate_practice_quiz(topic: str, num_questions: int = 5) -> str:
    """Generate a practice quiz."""
    _ensure_dirs()
    filename = f"{topic.replace(' ', '_').lower()}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    path = QUIZZES_DIR / filename

    questions = []
    for i in range(num_questions):
        questions.append({
            "number": i + 1,
            "question": f"Question {i+1} about {topic}",
            "options": ["Option A", "Option B", "Option C", "Option D"],
            "answer": "Option A",
            "explanation": f"This relates to a core concept in {topic}.",
        })

    quiz = {
        "topic": topic,
        "created_at": datetime.now().isoformat(),
        "questions": questions,
    }
    path.write_text(json.dumps(quiz, indent=2, ensure_ascii=False), encoding="utf-8")
    return str(path)


def list_generated_files(category: str = "") -> list[dict]:
    """List generated study materials."""
    _ensure_dirs()
    dirs = {
        "notes": NOTES_DIR,
        "flashcards": FLASHCARDS_DIR,
        "guides": GUIDES_DIR,
        "quizzes": QUIZZES_DIR,
    }

    results = []
    for cat, d in dirs.items():
        if category and cat != category:
            continue
        for file in sorted(d.glob("*"), reverse=True):
            results.append({
                "category": cat,
                "name": file.stem,
                "path": str(file),
                "size": file.stat().st_size,
                "created": datetime.fromtimestamp(file.stat().st_mtime).isoformat(),
            })

    return sorted(results, key=lambda x: x["created"], reverse=True)
