import { PageHeading } from "@/components/ui/page-heading";
import { SectionHeading } from "@/components/ui/section-heading";
import { ContentPanel } from "@/components/ui/content-panel";

const checklistItems = [
  { principle: "AI is Optional", status: "✓ Implemented", detail: "Core MVP works without any AI service. AI features are planned as optional future enhancements only." },
  { principle: "Deterministic Results", status: "✓ Implemented", detail: "All KPI calculations use deterministic formulas on static synthetic data. AI is not involved in any analytical output." },
  { principle: "Human Review Required", status: "✓ Planned", detail: "Any future AI-generated requirements or analysis will be clearly labeled and require human validation before use." },
  { principle: "AI Output Labeling", status: "✓ Planned", detail: "Future AI-generated content will be clearly identified as AI-generated with appropriate disclaimers." },
  { principle: "No Sensitive Data Submission", status: "✓ Implemented", detail: "The application contains no forms or inputs that could submit personal data to any service." },
  { principle: "Transparency", status: "✓ Implemented", detail: "This page documents all AI-related decisions and principles. No AI capabilities are hidden or misrepresented." },
  { principle: "Bias Awareness", status: "✓ Documented", detail: "Synthetic data is designed to demonstrate scenarios, not to make generalizations about any group or population." },
  { principle: "Auditability", status: "✓ Documented", detail: "All requirements, risks, and KPIs are documented with clear traceability. Any future AI additions will follow the same standard." },
  { principle: "Data Privacy", status: "✓ Implemented", detail: "No user data is collected, stored, or transmitted. No cookies, analytics, or tracking mechanisms are used." },
  { principle: "Stakeholder Validation", status: "✓ Documented", detail: "Requirements are defined through structured stakeholder analysis, not generated by AI without human oversight." },
];

export default function ResponsibleAiPage() {
  return (
    <div className="content-container py-8">
      <PageHeading title="Responsible AI" subtitle="Ethical AI considerations for the BA Compass project" />

      <ContentPanel className="mb-6">
        <SectionHeading title="Our Approach to AI" />
        <p className="text-surface-600">
          BA Compass is designed as a <strong>deterministic, AI-independent</strong> application.
          The public demo requires zero AI services, zero API keys, and zero external intelligence.
          This is intentional — recruiters must be able to evaluate the portfolio without configuring
          AI providers or incurring costs.
        </p>
        <p className="mt-3 text-surface-600">
          Any future AI integration will follow the principles documented on this page. AI will be
          an <strong>optional enhancement</strong>, never a requirement for core functionality.
        </p>
      </ContentPanel>

      {/* Responsible AI Checklist */}
      <ContentPanel className="mb-6">
        <SectionHeading title="Responsible AI Checklist" description="Principles guiding AI decisions in this project" />
        <div className="space-y-3">
          {checklistItems.map((item) => (
            <div key={item.principle} className="rounded-lg border border-surface-200 p-3">
              <div className="flex items-center justify-between">
                <h3 className="font-medium text-surface-800">{item.principle}</h3>
                <span className={`text-xs font-medium ${item.status.includes("✓") ? "text-green-600" : "text-amber-600"}`}>{item.status}</span>
              </div>
              <p className="mt-1 text-sm text-surface-500">{item.detail}</p>
            </div>
          ))}
        </div>
      </ContentPanel>

      {/* Risk Considerations */}
      <div className="mb-6 grid gap-4 sm:grid-cols-2">
        <ContentPanel>
          <SectionHeading title="AI Risk Considerations" />
          <ul className="list-inside list-disc space-y-1 text-sm text-surface-600">
            <li><strong>Hallucination risk:</strong> AI-generated content may contain plausible but incorrect information. All future AI output will be labeled and require review.</li>
            <li><strong>Bias risk:</strong> AI models can perpetuate biases present in training data. Synthetic data and analysis will be reviewed for unintended bias.</li>
            <li><strong>Over-reliance risk:</strong> AI recommendations are not substitutes for stakeholder validation and business judgment.</li>
            <li><strong>Privacy risk:</strong> No sensitive data will be submitted to AI services. All synthetic data is clearly labeled as fictional.</li>
          </ul>
        </ContentPanel>
        <ContentPanel>
          <SectionHeading title="Data Ethics Commitments" />
          <ul className="list-inside list-disc space-y-1 text-sm text-surface-600">
            <li>All project data is synthetic and clearly labeled on every page</li>
            <li>No real personal information is stored, processed, or transmitted</li>
            <li>No user tracking, analytics, or data collection occurs</li>
            <li>No cookies, session storage, or persistent identifiers are used</li>
            <li>The application is privacy-preserving by design and by default</li>
            <li>All code is inspectable — no hidden data collection mechanisms</li>
          </ul>
        </ContentPanel>
      </div>

      {/* Transparency Note */}
      <ContentPanel>
        <SectionHeading title="Transparency Note" />
        <p className="text-sm text-surface-600">
          This application was built with assistance from AI tools. Every piece of analysis content
          (requirements, stakeholder analysis, process maps, KPIs, risks) was reviewed, validated,
          and edited by a human Business Analyst (Titus Banks). AI was used as a productivity tool
          for code generation and content drafting — never as the decision-maker for analytical
          conclusions.
        </p>
        <p className="mt-3 text-sm text-surface-500">
          The Business Analyst methodology, requirement definitions, KPI formulas, and analytical
          framework are the work of Titus Banks. AI tools accelerated the implementation but did
          not define the analytical approach.
        </p>
      </ContentPanel>

      <div className="mt-6 flex justify-between">
        <a href="/project" className="text-sm font-medium text-brand-600 hover:text-brand-700">← About the Project</a>
        <a href="/overview" className="text-sm font-medium text-brand-600 hover:text-brand-700">Back to Start</a>
      </div>
    </div>
  );
}
