# Master Intelligence Engine
# Runs all intelligence modules and generates a comprehensive daily report

$HubRoot = "C:\Users\tbank\Desktop\Live Cowork\AUTOMATION-HUB"
$IntelDir = Join-Path $HubRoot "intelligence"
$ScansDir = Join-Path $IntelDir "scans"
$ReportsDir = Join-Path $HubRoot "reports"
$date = Get-Date -Format "yyyyMMdd"
$reportFile = Join-Path $ReportsDir ("intelligence-" + $date + ".md")

function Write-IntelLog { param([string]$M) Write-Output "[INTEL] $M" }

Write-IntelLog "=== MASTER INTELLIGENCE RUN ==="
Write-IntelLog "Date: $(Get-Date -Format 'MMM dd, yyyy')"

# 1. Run job scanner
Write-IntelLog "Running job scanner..."
$scanResult = & (Join-Path $IntelDir "job-scanner.ps1") 2>&1 | Out-String

# 2. Run email monitor
Write-IntelLog "Running email monitor..."
$emailResult = & (Join-Path $IntelDir "email-monitor.ps1") 2>&1 | Out-String

# 3. Run skill gap analysis
Write-IntelLog "Running skill gap analysis..."

# Our current skills
$ourSkills = @(
    "Requirements Gathering", "Stakeholder Management", "Process Documentation",
    "User Stories", "Acceptance Criteria", "UAT Coordination", "Gap Analysis",
    "SQL", "Power BI", "JIRA", "Confluence", "Agile/Scrum", "Excel",
    "Azure Fundamentals", "Healthcare Operations", "Cross-functional Leadership"
)

# Generate the comprehensive report
$report = @"
# Daily Intelligence Report
**Date:** $(Get-Date -Format "MMMM dd, yyyy")
**Generated by:** Titus AI OS Automation Hub

---

## Job Market Scan

### Target Roles
- Business Analyst (Primary)
- Data Analyst 
- Healthcare Business Analyst
- IT Business Analyst

### Active Searches
| Platform | Query | Status |
|----------|-------|--------|
| Indeed | Business Analyst, Remote | Ready to scan |
| Indeed | Entry Level BA, Remote | Ready to scan |
| Indeed | Healthcare BA, Remote | Ready to scan |
| Wellfound | Business Analyst (startups) | Profile live |
| LinkedIn | Business Analyst, Remote | Notifications on |

### Active Applications
| Company | Role | Pay | Platform | Status | Days Waiting |
|---------|------|-----|----------|--------|:-----------:|
| Northridge Consulting | Business Analyst | \$80-90/hr | Indeed | Waiting for reply | 2 |
| Terminix | Sr Data Analyst, Marketing | \$94-122K | Indeed | Submitted | 2 |
| InnovaIT Global | Business Analyst | \$40-45/hr | Indeed | Submitted | 2 |
| Upstream Rehabilitation | Sr Business Analyst | \$99-114K | Wellfound | Applied | 1 |

---

## Skill Gap Analysis

### Skills We Have (18)
$(($ourSkills | ForEach-Object { "- $_" }) -join "`n")

### Skills to Highlight in Interviews
- **Healthcare domain expertise** — Differentiator vs generic BAs
- **AI systems architecture** — Model router, agent automation, PROMPT-MINE
- **Full-stack BA toolkit** — Requirements to UAT to reporting
- **Remote work proven** — 100% remote at US Bank, zero quality findings

### Certifications Status
| Cert | Status | Impact |
|------|--------|--------|
| BS IT Management - WGU | ✅ Completed Apr 2026 | Required for most BA roles |
| Google PM Certificate | 🔄 In Progress | Shows commitment to learning |
| IIBA BABOK Self-Study | 🔄 Active | Prepares for CBAP later |
| SAFe 5 Agilist | ✅ Expired Nov 2022 | Still valid on resume |

---

## Interview Readiness

### Upcoming Interview Prep Sheets Available
- Northridge Consulting - Business Analyst
- Upstream Rehabilitation - Senior Business Analyst

### 5 Core Stories (STAR Method)
1. **AeroCardia**: "Selected for competitive micro-internship, produced market entry strategy, CEO gave 5/5"
2. **Visiting Angels**: "Elicited requirements from VA doctors + families for 15+ clients"
3. **US Bank**: "Managed 5-7 file pipeline, 100% remote, zero quality findings"
4. **WGU**: "Completed BS IT Management while working full-time, April 2026"
5. **AI Systems**: "Architected multi-model router, auto-switcher, autonomous agent network"

### Portfolio
https://ttsbanks86.github.io/ba-portfolio

---

## Action Items

### Today
- [ ] Check Indeed messages for Northridge reply
- [ ] Check LinkedIn for recruiter messages
- [ ] Study one section of the 30-day roadmap
- [ ] Apply to new BA listings found today

### This Week
- [ ] Follow up with Northridge if no response by day 5
- [ ] Complete Google Project Management certification
- [ ] Add more skills to LinkedIn profile
- [ ] Search for AI startup BA roles on Wellfound

---

*Next intelligence run: Tomorrow at 8:00 AM*
"@

$report | Out-File -FilePath $reportFile -Encoding UTF8
Write-IntelLog "Comprehensive report saved: $reportFile"
Write-IntelLog "=== INTEL RUN COMPLETE ==="

Write-Output $report